import math
from abc import ABC, abstractmethod
from typing import TypeVar
from layers_edx.element import Element, Composition
from layers_edx.roi import RegionOfInterest, RegionOfInterestSet
from layers_edx.xrt import XRayTransition


class StandardMaterial(ABC):
    """Encapsulates the data associated with a standard material with the data of a specific element."""

    def __init__(self,
                 element: Element,
                 composition: Composition,
                 stripped_elements: set[Element] = None,
                 min_intensity: float = 1.0e-3):
        self._element = element
        self._composition = composition
        self._stripped_elements = set() if stripped_elements is None else stripped_elements
        self._min_intensity = min_intensity
        self._required_references: dict[RegionOfInterest, set[RegionOfInterest]] = {}
        self._compute_roi_sets()
        self._compute_required_references()
        self._intensities: dict[RegionOfInterest, dict[XRayTransition, float]] = {}

    @abstractmethod
    def create_element_roi_set(self, element: Element) -> RegionOfInterestSet:
        pass

    def _compute_roi_sets(self) -> None:
        self._roi_set = self.create_element_roi_set(self.element)
        all_elements = set(self.composition.elements) | self.stripped_elements
        self._other_roi_sets = {element: self.create_element_roi_set(element) for element in all_elements}
        self._all_roi_set = self._other_roi_sets.pop(self.element)
        for roi_set in self._other_roi_sets.values():
            for roi in roi_set.rois:
                self._all_roi_set.add_roi(roi)

    def _compute_required_references(self) -> None:
        for roi in self.roi_set.rois:
            required_references = set()
            for all_roi in self._all_roi_set.rois:
                if roi.intersects(all_roi):
                    for other in self._other_roi_sets:
                        for other_roi in self._other_roi_sets[other].rois:
                            if other_roi.intersects(all_roi):
                                required_references.add(other_roi)
                                required_references.add(roi)
            self._required_references[roi] = required_references

    @property
    def element(self) -> Element:
        return self._element

    @property
    def composition(self) -> Composition:
        """The composition of the standard."""
        return self._composition

    @property
    def roi_set(self) -> RegionOfInterestSet:
        return self._roi_set

    @property
    def stripped_elements(self) -> set[Element]:
        return self._stripped_elements

    @property
    def min_intensity(self) -> float:
        """The minimum weighted intensity for an X-ray transition to be considered."""
        return self._min_intensity

    @property
    def required_references(self) -> dict[RegionOfInterest, set[RegionOfInterest]]:
        return self._required_references

    def is_suitable_as_reference(self, roi: RegionOfInterest) -> bool:
        if roi.first_element == self.element:
            return roi not in self.required_references[roi]
        return roi in self._all_roi_set.rois

    @abstractmethod
    def compute_intensities(self, roi: RegionOfInterest) -> dict[XRayTransition, float]:
        pass

    def intensities(self, roi: RegionOfInterest) -> dict[XRayTransition, float]:
        """Returns the x-ray intensities generated by this standard on the specified ``RegionOfInterest``."""
        if roi not in self._intensities:
            self._intensities[roi] = self.compute_intensities(roi)
        return self._intensities[roi]

    def total_intensity(self, roi: RegionOfInterest) -> float:
        """Returns the integrated x-ray intensity generated by this standard on the specified ``RegionOfInterest``."""
        return sum(self.intensities(roi).values())

    def nominal_signal_to_noise(self, roi: RegionOfInterest) -> float:
        """Computes the nominal signal-to-noise ratio on the specified ``RegionOfInterest``."""
        return math.sqrt(self.total_intensity(roi)) if roi.first_element in self.composition else 0.0


TStandardMaterial = TypeVar('TStandardMaterial', bound=StandardMaterial)